<?php
require_once __DIR__.'/_init.php';
PA_KasirBridge::ensureTables($pdo);
$title='Ringkasan Multi File';
$token=trim((string)($_GET['token']??''));
if($token===''){ http_response_code(404); exit('Batch tidak ditemukan.'); }
$st=$pdo->prepare('SELECT j.*, pp.* , j.id job_id, pp.name profile_name FROM print_jobs j LEFT JOIN price_profiles pp ON pp.id=j.price_profile_id WHERE j.batch_token=? ORDER BY j.id');
$st->execute([$token]);
$jobs=$st->fetchAll(PDO::FETCH_ASSOC);
if(!$jobs){ http_response_code(404); exit('Batch tidak ditemukan.'); }
$ids=array_map(fn($j)=>(int)$j['job_id'],$jobs);
$summary=['total_pages'=>0,'bw_pages'=>0,'color_25_pages'=>0,'color_50_pages'=>0,'color_75_pages'=>0,'color_100_pages'=>0,'estimated_total'=>0];
$convertedNo='';
foreach($jobs as $j){
    foreach($summary as $k=>$_){ $summary[$k]+=(float)($j[$k]??0); }
    if(!empty($j['no_penjualan'])) $convertedNo=$j['no_penjualan'];
}
$pelanggan=$pdo->query('SELECT kode_pelanggan,nama_pelanggan,no_telepon FROM pelanggan ORDER BY nama_pelanggan LIMIT 800')->fetchAll(PDO::FETCH_ASSOC);
require __DIR__.'/_header.php'; ?>
<style>
.pa-summary-card{border:0;border-radius:18px;box-shadow:0 10px 24px rgba(15,23,42,.08)}
.pa-step{display:flex;gap:12px;align-items:flex-start}.pa-step-no{width:30px;height:30px;border-radius:999px;background:#0d6efd;color:white;display:flex;align-items:center;justify-content:center;font-weight:700;flex:0 0 30px}.pa-section-title{font-weight:700;margin-bottom:2px}.pa-total-box{background:linear-gradient(135deg,#0d6efd,#0aa2c0);color:white;border-radius:18px;padding:18px}.pa-total-box .muted{color:rgba(255,255,255,.75)}.pa-pay-option input{display:none}.pa-pay-option span{display:block;border:1px solid #dbe3ef;border-radius:12px;padding:12px 14px;background:#fff;cursor:pointer;text-align:center;font-weight:600}.pa-pay-option input:checked+span{border-color:#0d6efd;background:#eaf3ff;color:#0d6efd;box-shadow:0 0 0 3px rgba(13,110,253,.12)}.pa-customer-select{position:relative}.pa-customer-menu{position:absolute;z-index:20;left:0;right:0;top:100%;background:#fff;border:1px solid #dbe3ef;border-radius:14px;margin-top:6px;box-shadow:0 16px 40px rgba(15,23,42,.18);max-height:260px;overflow:auto;display:none}.pa-customer-item{padding:10px 12px;cursor:pointer;border-bottom:1px solid #f1f5f9}.pa-customer-item:hover{background:#f1f7ff}.pa-pill{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:6px 10px;background:#f1f5f9;color:#334155;font-size:.85rem}
</style>
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><div class="d-flex justify-content-between flex-wrap gap-2"><div><h4 class="mb-1">Multi File Analyzer</h4><div class="text-muted"><?= count($jobs) ?> file · <?= e($jobs[0]['profile_name'] ?? '-') ?> · <?= e(date('d/m/Y H:i',strtotime($jobs[0]['created_at']))) ?></div></div><div class="text-end"><h4 class="text-primary mb-0"><?= rupiah($summary['estimated_total']) ?></h4><small class="text-muted">Estimasi 1 rangkap semua file</small></div></div></div></div>
<div class="row g-2 mb-4"><div class="col"><div class="card"><div class="card-body p-3"><small>Total Halaman</small><h5><?= (int)$summary['total_pages'] ?></h5></div></div></div><div class="col"><div class="card"><div class="card-body p-3"><small>BW</small><h5><?= (int)$summary['bw_pages'] ?></h5></div></div></div><div class="col"><div class="card"><div class="card-body p-3"><small>25%</small><h5><?= (int)$summary['color_25_pages'] ?></h5></div></div></div><div class="col"><div class="card"><div class="card-body p-3"><small>50%</small><h5><?= (int)$summary['color_50_pages'] ?></h5></div></div></div><div class="col"><div class="card"><div class="card-body p-3"><small>75%</small><h5><?= (int)$summary['color_75_pages'] ?></h5></div></div></div><div class="col"><div class="card"><div class="card-body p-3"><small>100%</small><h5><?= (int)$summary['color_100_pages'] ?></h5></div></div></div></div>

<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white"><b>Daftar File</b><br><small class="text-muted">Klik koreksi bila ada file yang kategori halamannya perlu diubah sebelum transaksi dibuat.</small></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>File</th><th class="text-end">Halaman</th><th>Ringkasan</th><th class="text-end">Estimasi</th><th>Aksi</th></tr></thead><tbody><?php foreach($jobs as $j): ?><tr><td><b><?= e($j['original_filename']) ?></b><br><small class="text-muted">Job #<?= (int)$j['job_id'] ?> · <?= e($j['status']) ?></small><?php if($j['status']==='failed'): ?><div class="text-danger small"><?= e($j['error_message']) ?></div><?php endif; ?></td><td class="text-end"><?= (int)$j['total_pages'] ?></td><td><small>BW <?= (int)$j['bw_pages'] ?> · 25% <?= (int)$j['color_25_pages'] ?> · 50% <?= (int)$j['color_50_pages'] ?> · 75% <?= (int)$j['color_75_pages'] ?> · 100% <?= (int)$j['color_100_pages'] ?></small></td><td class="text-end"><b><?= rupiah($j['estimated_total']) ?></b></td><td><a class="btn btn-sm btn-outline-primary" href="job.php?id=<?= (int)$j['job_id'] ?>">Preview / Koreksi</a></td></tr><?php endforeach; ?></tbody></table></div></div>

<?php if($convertedNo): ?>
<div class="alert alert-success">Batch ini sudah menjadi transaksi: <b><?= e($convertedNo) ?></b> · <a href="../penjualan/cetak.php?no=<?= urlencode($convertedNo) ?>">Cetak Nota</a></div>
<?php else: ?>
<div class="card pa-summary-card mb-4"><div class="card-header bg-white border-0 pt-4 px-4"><div class="d-flex justify-content-between align-items-start flex-wrap gap-2"><div><h4 class="mb-1"><i class="fas fa-cash-register text-success"></i> Jadikan Transaksi Kasir</h4><div class="text-muted">Semua file di atas akan digabung menjadi satu transaksi kasir.</div></div><span class="pa-pill"><i class="fas fa-file-alt"></i> <?= count($jobs) ?> file</span></div></div><div class="card-body p-4"><form method="post" action="jadikan_transaksi_multi.php" id="kasirForm"><input type="hidden" name="_csrf" value="<?= e(pa_csrf()) ?>"><input type="hidden" name="batch_token" value="<?= e($token) ?>"><input type="hidden" name="kode_pelanggan" id="kodePelangganInput" value="UMUM">
<div class="row g-4"><div class="col-lg-8"><div class="pa-step mb-4"><div class="pa-step-no">1</div><div class="flex-grow-1"><div class="pa-section-title">Pelanggan</div><small class="text-muted">Cari nama atau nomor pelanggan. Default boleh UMUM.</small><div class="pa-customer-select mt-2"><input type="text" class="form-control form-control-lg" id="customerSearch" value="UMUM" autocomplete="off" placeholder="Ketik nama / nomor pelanggan"><div class="pa-customer-menu" id="customerMenu"><div class="pa-customer-item" data-kode="UMUM" data-label="UMUM"><b>UMUM</b><small>Pelanggan umum / tanpa data pelanggan</small></div><?php foreach($pelanggan as $pl): $label=trim($pl['nama_pelanggan'].($pl['no_telepon']?' - '.$pl['no_telepon']:'')); ?><div class="pa-customer-item" data-kode="<?= e($pl['kode_pelanggan']) ?>" data-label="<?= e($label) ?>"><b><?= e($pl['nama_pelanggan']) ?></b><small><?= e($pl['kode_pelanggan']) ?><?= $pl['no_telepon']?' · '.e($pl['no_telepon']):'' ?></small></div><?php endforeach; ?></div></div></div></div>
<div class="pa-step mb-4"><div class="pa-step-no">2</div><div class="flex-grow-1"><div class="pa-section-title">Detail Cetak</div><div class="row g-3 mt-1"><div class="col-md-4"><label class="form-label">Qty / Rangkap</label><div class="input-group input-group-lg"><button type="button" class="btn btn-outline-secondary" id="qtyMinus">-</button><input class="form-control text-center" type="number" name="qty_cetak" id="qtyCetak" min="1" value="1"><button type="button" class="btn btn-outline-secondary" id="qtyPlus">+</button></div></div><div class="col-md-4"><label class="form-label">Finishing</label><input class="form-control form-control-lg" name="finishing" placeholder="Contoh: jilid / laminating"></div><div class="col-md-4"><label class="form-label">Catatan</label><input class="form-control form-control-lg" name="catatan" placeholder="Catatan order"></div></div></div></div>
<div class="pa-step"><div class="pa-step-no">3</div><div class="flex-grow-1"><div class="pa-section-title">Pembayaran</div><div class="row g-3 mt-1"><div class="col-md-4"><label class="pa-pay-option"><input type="radio" name="metode" value="Cash" checked><span><i class="fas fa-money-bill"></i> Cash</span></label></div><div class="col-md-4"><label class="pa-pay-option"><input type="radio" name="metode" value="QRIS"><span><i class="fas fa-qrcode"></i> QRIS</span></label></div><div class="col-md-4"><label class="pa-pay-option"><input type="radio" name="metode" value="Utang"><span><i class="fas fa-clock"></i> Utang</span></label></div><div class="col-md-6"><label class="form-label">Uang Bayar</label><input class="form-control form-control-lg" type="number" name="uang_bayar" id="uangBayar" value="<?= (int)$summary['estimated_total'] ?>" min="0"></div><div class="col-md-6 d-flex align-items-end gap-2 flex-wrap"><button type="button" class="btn btn-outline-success" id="btnLunas">Bayar Lunas</button><button type="button" class="btn btn-outline-warning" id="btnDp50">DP 50%</button><button type="button" class="btn btn-outline-secondary" id="btnUtang">Utang</button></div></div></div></div></div>
<div class="col-lg-4"><div class="pa-total-box mb-3"><div class="muted">Total transaksi</div><h2 class="mb-2" id="totalText"><?= rupiah($summary['estimated_total']) ?></h2><div class="d-flex justify-content-between"><span class="muted">Bayar</span><b id="bayarText"><?= rupiah($summary['estimated_total']) ?></b></div><div class="d-flex justify-content-between"><span class="muted" id="statusLabel">Kembalian</span><b id="statusText">Rp0</b></div></div><div class="card border-0 bg-light"><div class="card-body"><b>Ringkasan gabungan</b><div class="small text-muted mt-2">Total <?= (int)$summary['total_pages'] ?> halaman dari <?= count($jobs) ?> file.</div><ul class="list-unstyled mt-2 mb-0 small"><li>BW: <?= (int)$summary['bw_pages'] ?> halaman</li><li>Warna 25%: <?= (int)$summary['color_25_pages'] ?> halaman</li><li>Warna 50%: <?= (int)$summary['color_50_pages'] ?> halaman</li><li>Warna 75%: <?= (int)$summary['color_75_pages'] ?> halaman</li><li>Warna 100%: <?= (int)$summary['color_100_pages'] ?> halaman</li></ul></div></div><button class="btn btn-success btn-lg w-100 mt-3"><i class="fas fa-check"></i> Buat Transaksi Gabungan</button></div></div></form></div></div>
<script>
(function(){
 const base=<?= (float)$summary['estimated_total'] ?>, qty=document.getElementById('qtyCetak'), uang=document.getElementById('uangBayar'), totalText=document.getElementById('totalText'), bayarText=document.getElementById('bayarText'), statusText=document.getElementById('statusText'), statusLabel=document.getElementById('statusLabel'), metodeInputs=document.querySelectorAll('input[name="metode"]');
 const rp=n=>'Rp'+Math.round(n).toLocaleString('id-ID');
 function total(){return base*Math.max(1,Number(qty.value||1));}
 function refresh(){const t=total(), b=Number(uang.value||0); totalText.textContent=rp(t); bayarText.textContent=rp(b); if(b>=t){statusLabel.textContent='Kembalian'; statusText.textContent=rp(b-t);}else{statusLabel.textContent='Piutang'; statusText.textContent=rp(t-b);} }
 qty.addEventListener('input',()=>{ if(Number(qty.value)<1) qty.value=1; refresh(); }); uang.addEventListener('input',refresh);
 document.getElementById('qtyMinus').onclick=()=>{qty.value=Math.max(1,Number(qty.value||1)-1); uang.value=Math.round(total()); refresh();};
 document.getElementById('qtyPlus').onclick=()=>{qty.value=Number(qty.value||1)+1; uang.value=Math.round(total()); refresh();};
 document.getElementById('btnLunas').onclick=()=>{ uang.value=Math.round(total()); metodeInputs.forEach(i=>{if(i.value==='Cash')i.checked=true}); refresh(); };
 document.getElementById('btnDp50').onclick=()=>{ uang.value=Math.round(total()/2); refresh(); };
 document.getElementById('btnUtang').onclick=()=>{ uang.value=0; metodeInputs.forEach(i=>{if(i.value==='Utang')i.checked=true}); refresh(); };
 metodeInputs.forEach(i=>i.addEventListener('change',()=>{ if(i.checked && i.value==='Utang'){ uang.value=0; refresh(); } }));
 const search=document.getElementById('customerSearch'), menu=document.getElementById('customerMenu'), hidden=document.getElementById('kodePelangganInput');
 function items(){ return Array.from(menu.querySelectorAll('.pa-customer-item')); }
 function openMenu(){ menu.style.display='block'; filter(); }
 function closeMenu(){ setTimeout(()=>menu.style.display='none',180); }
 function choose(el){ hidden.value=el.dataset.kode; search.value=el.dataset.label; menu.style.display='none'; }
 function filter(){ const q=search.value.toLowerCase().trim(); items().forEach(el=>{ const txt=(el.textContent||'').toLowerCase(); el.style.display=(!q || txt.includes(q))?'block':'none'; }); }
 search.addEventListener('focus',openMenu); search.addEventListener('click',openMenu); search.addEventListener('blur',closeMenu); search.addEventListener('input',()=>{ hidden.value='UMUM'; filter(); openMenu(); });
 items().forEach(el=>el.addEventListener('mousedown',e=>{e.preventDefault(); choose(el);}));
 document.getElementById('kasirForm').addEventListener('submit',function(e){ if(!confirm('Buat satu transaksi kasir dari semua file ini?')) e.preventDefault(); });
 refresh();
})();
</script>
<?php endif; ?>
<?php require __DIR__.'/_footer.php'; ?>
