<?php require_once __DIR__.'/_init.php'; PA_KasirBridge::ensureTables($pdo); $title='Hasil Analisis'; $id=(int)($_GET['id']??0);
$st=$pdo->prepare('SELECT j.*, pp.* , j.id job_id, pp.name profile_name FROM print_jobs j LEFT JOIN price_profiles pp ON pp.id=j.price_profile_id WHERE j.id=?'); $st->execute([$id]); $job=$st->fetch(PDO::FETCH_ASSOC); if(!$job){ http_response_code(404); exit('Data tidak ditemukan.'); }
$pg=$pdo->prepare('SELECT * FROM print_job_pages WHERE print_job_id=? ORDER BY page_number'); $pg->execute([$id]); $pages=$pg->fetchAll(PDO::FETCH_ASSOC);
$pelanggan=$pdo->query('SELECT kode_pelanggan,nama_pelanggan,no_telepon FROM pelanggan ORDER BY nama_pelanggan LIMIT 800')->fetchAll(PDO::FETCH_ASSOC);
$baseTotal=(float)($job['estimated_total'] ?? 0);
$batchCount=0;
if(!empty($job['batch_token'])){ $bc=$pdo->prepare('SELECT COUNT(*) FROM print_jobs WHERE batch_token=?'); $bc->execute([$job['batch_token']]); $batchCount=(int)$bc->fetchColumn(); }
require __DIR__.'/_header.php'; ?>
<style>
.pa-summary-card{border:0;border-radius:18px;box-shadow:0 10px 24px rgba(15,23,42,.08)}
.pa-step{display:flex;gap:12px;align-items:flex-start}.pa-step-no{width:30px;height:30px;border-radius:999px;background:#0d6efd;color:white;display:flex;align-items:center;justify-content:center;font-weight:700;flex:0 0 30px}.pa-section-title{font-weight:700;margin-bottom:2px}.pa-soft{background:#f8fafc;border:1px solid #e5e7eb;border-radius:16px}.pa-total-box{background:linear-gradient(135deg,#0d6efd,#0aa2c0);color:white;border-radius:18px;padding:18px}.pa-total-box .muted{color:rgba(255,255,255,.75)}.pa-pay-option input{display:none}.pa-pay-option span{display:block;border:1px solid #dbe3ef;border-radius:12px;padding:12px 14px;background:#fff;cursor:pointer;text-align:center;font-weight:600}.pa-pay-option input:checked+span{border-color:#0d6efd;background:#eaf3ff;color:#0d6efd;box-shadow:0 0 0 3px rgba(13,110,253,.12)}.pa-customer-select{position:relative}.pa-customer-menu{position:absolute;z-index:20;left:0;right:0;top:100%;background:#fff;border:1px solid #dbe3ef;border-radius:14px;margin-top:6px;box-shadow:0 16px 40px rgba(15,23,42,.18);max-height:260px;overflow:auto;display:none}.pa-customer-item{padding:10px 12px;cursor:pointer;border-bottom:1px solid #f1f5f9}.pa-customer-item:hover,.pa-customer-item.active{background:#f1f7ff}.pa-customer-item small{display:block;color:#64748b}.pa-pill{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:6px 10px;background:#f1f5f9;color:#334155;font-size:.85rem}.pa-mobile-sticky{position:sticky;bottom:12px;z-index:10}
</style>
<?php if($batchCount>1): ?><div class="alert alert-info d-flex justify-content-between align-items-center"><span>File ini bagian dari upload multi-file.</span><a class="btn btn-sm btn-primary" href="batch.php?token=<?= urlencode($job['batch_token']) ?>">Kembali ke Ringkasan Gabungan</a></div><?php endif; ?>
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><div class="d-flex justify-content-between flex-wrap gap-2"><div><h4 class="mb-1"><?= e($job['original_filename']) ?></h4><div class="text-muted"><?= e($job['profile_name'] ?? '-') ?> · <?= e(date('d/m/Y H:i',strtotime($job['created_at']))) ?></div><?php if($job['status']==='failed'): ?><div class="alert alert-danger mt-2 mb-0"><?= e($job['error_message']) ?></div><?php endif; ?></div><div class="text-end"><h4 class="text-primary mb-0"><?= rupiah($baseTotal) ?></h4><small class="text-muted">Estimasi 1 rangkap</small></div></div></div></div>
<div class="row g-2 mb-4"><div class="col"><div class="card"><div class="card-body p-3"><small>BW</small><h5><?= (int)$job['bw_pages'] ?></h5></div></div></div><div class="col"><div class="card"><div class="card-body p-3"><small>25%</small><h5><?= (int)$job['color_25_pages'] ?></h5></div></div></div><div class="col"><div class="card"><div class="card-body p-3"><small>50%</small><h5><?= (int)$job['color_50_pages'] ?></h5></div></div></div><div class="col"><div class="card"><div class="card-body p-3"><small>75%</small><h5><?= (int)$job['color_75_pages'] ?></h5></div></div></div><div class="col"><div class="card"><div class="card-body p-3"><small>100%</small><h5><?= (int)$job['color_100_pages'] ?></h5></div></div></div></div>
<?php if(!$job['no_penjualan'] && $batchCount <= 1): ?>
<div class="card pa-summary-card mb-4"><div class="card-header bg-white border-0 pt-4 px-4"><div class="d-flex justify-content-between align-items-start flex-wrap gap-2"><div><h4 class="mb-1"><i class="fas fa-cash-register text-success"></i> Jadikan Transaksi Kasir</h4><div class="text-muted">Lengkapi pelanggan, rangkap cetak, pembayaran, dan catatan pekerjaan.</div></div><span class="pa-pill"><i class="fas fa-file-alt"></i> <?= (int)$job['total_pages'] ?> halaman</span></div></div><div class="card-body p-4"><form method="post" action="jadikan_transaksi.php" id="kasirForm"><input type="hidden" name="_csrf" value="<?= e(pa_csrf()) ?>"><input type="hidden" name="job_id" value="<?= (int)$id ?>"><input type="hidden" name="kode_pelanggan" id="kodePelangganInput" value="UMUM">
<div class="row g-4"><div class="col-lg-8"><div class="pa-step mb-4"><div class="pa-step-no">1</div><div class="flex-grow-1"><div class="pa-section-title">Pelanggan</div><small class="text-muted">Cari nama atau nomor pelanggan. Default boleh UMUM.</small><div class="pa-customer-select mt-2"><input type="text" class="form-control form-control-lg" id="customerSearch" value="UMUM" autocomplete="off" placeholder="Ketik nama / nomor pelanggan"><div class="pa-customer-menu" id="customerMenu"><div class="pa-customer-item" data-kode="UMUM" data-label="UMUM"><b>UMUM</b><small>Pelanggan umum / tanpa data pelanggan</small></div><?php foreach($pelanggan as $pl): $label=trim($pl['nama_pelanggan'].($pl['no_telepon']?' - '.$pl['no_telepon']:'')); ?><div class="pa-customer-item" data-kode="<?= e($pl['kode_pelanggan']) ?>" data-label="<?= e($label) ?>"><b><?= e($pl['nama_pelanggan']) ?></b><small><?= e($pl['kode_pelanggan']) ?><?= $pl['no_telepon']?' · '.e($pl['no_telepon']):'' ?></small></div><?php endforeach; ?></div></div></div></div>
<div class="pa-step mb-4"><div class="pa-step-no">2</div><div class="flex-grow-1"><div class="pa-section-title">Detail Cetak</div><div class="row g-3 mt-1"><div class="col-md-4"><label class="form-label">Qty / Rangkap</label><div class="input-group input-group-lg"><button type="button" class="btn btn-outline-secondary" id="qtyMinus">-</button><input class="form-control text-center" type="number" name="qty_cetak" id="qtyCetak" value="1" min="1" required><button type="button" class="btn btn-outline-secondary" id="qtyPlus">+</button></div></div><div class="col-md-8"><label class="form-label">Finishing</label><input class="form-control form-control-lg" name="finishing" placeholder="Contoh: jilid lakban, laminating, potong, tanpa finishing"></div><div class="col-12"><label class="form-label">Catatan pekerjaan</label><textarea class="form-control" name="catatan" rows="3" placeholder="Contoh: print bolak-balik, halaman tertentu saja, jangan distaples, ambil sore"></textarea></div></div></div></div>
<div class="pa-step"><div class="pa-step-no">3</div><div class="flex-grow-1"><div class="pa-section-title">Pembayaran</div><small class="text-muted">Pilih metode pembayaran dan nominal bayar.</small><div class="row g-2 mt-2"><div class="col-6 col-md-3"><label class="pa-pay-option"><input type="radio" name="metode" value="Cash" checked><span><i class="fas fa-money-bill-wave"></i><br>Cash</span></label></div><div class="col-6 col-md-3"><label class="pa-pay-option"><input type="radio" name="metode" value="QRIS"><span><i class="fas fa-qrcode"></i><br>QRIS</span></label></div><div class="col-6 col-md-3"><label class="pa-pay-option"><input type="radio" name="metode" value="Transfer"><span><i class="fas fa-building-columns"></i><br>Transfer</span></label></div><div class="col-6 col-md-3"><label class="pa-pay-option"><input type="radio" name="metode" value="Utang"><span><i class="fas fa-hand-holding-dollar"></i><br>Utang</span></label></div></div><div class="row g-3 mt-2"><div class="col-md-5"><label class="form-label">Uang bayar</label><input class="form-control form-control-lg" type="number" name="uang_bayar" id="uangBayar" value="<?= (int)$baseTotal ?>" min="0"></div><div class="col-md-7 d-flex align-items-end gap-2 flex-wrap"><button type="button" class="btn btn-outline-primary" id="btnLunas">Bayar Lunas</button><button type="button" class="btn btn-outline-secondary" id="btnDp50">DP 50%</button><button type="button" class="btn btn-outline-danger" id="btnUtang">Utang</button></div></div></div></div></div>
<div class="col-lg-4"><div class="pa-total-box mb-3"><div class="muted">Total transaksi</div><h2 class="mb-1" id="totalText"><?= rupiah($baseTotal) ?></h2><div class="muted">Estimasi 1 rangkap: <?= rupiah($baseTotal) ?></div><hr style="border-color:rgba(255,255,255,.35)"><div class="d-flex justify-content-between"><span>Uang bayar</span><b id="bayarText"><?= rupiah($baseTotal) ?></b></div><div class="d-flex justify-content-between"><span id="selisihLabel">Kembalian</span><b id="selisihText">Rp0</b></div></div><div class="pa-soft p-3 mb-3"><b>Ringkasan halaman</b><div class="table-responsive mt-2"><table class="table table-sm mb-0"><tbody><tr><td>Hitam Putih</td><td class="text-end"><?= (int)$job['bw_pages'] ?></td></tr><tr><td>Warna 25%</td><td class="text-end"><?= (int)$job['color_25_pages'] ?></td></tr><tr><td>Warna 50%</td><td class="text-end"><?= (int)$job['color_50_pages'] ?></td></tr><tr><td>Warna 75%</td><td class="text-end"><?= (int)$job['color_75_pages'] ?></td></tr><tr><td>Warna 100%</td><td class="text-end"><?= (int)$job['color_100_pages'] ?></td></tr></tbody></table></div></div><div class="pa-mobile-sticky"><button class="btn btn-success btn-lg w-100 shadow" id="submitTransaksi"><i class="fas fa-check-circle"></i> Buat Transaksi Kasir</button><a href="job.php?id=<?= (int)$id ?>" class="btn btn-light w-100 mt-2">Batal</a></div></div></div></form></div></div>
<script>
(function(){
 const baseTotal = <?= json_encode($baseTotal) ?>;
 const qty = document.getElementById('qtyCetak');
 const uang = document.getElementById('uangBayar');
 const totalText = document.getElementById('totalText');
 const bayarText = document.getElementById('bayarText');
 const selisihText = document.getElementById('selisihText');
 const selisihLabel = document.getElementById('selisihLabel');
 const metodeInputs = document.querySelectorAll('input[name="metode"]');
 const rupiah = n => 'Rp' + Math.round(Number(n||0)).toLocaleString('id-ID');
 function total(){ return Math.max(1, parseInt(qty.value||'1',10)) * baseTotal; }
 function refresh(){ const t=total(); const b=Number(uang.value||0); totalText.textContent=rupiah(t); bayarText.textContent=rupiah(b); const diff=b-t; if(diff>=0){selisihLabel.textContent='Kembalian'; selisihText.textContent=rupiah(diff);} else {selisihLabel.textContent='Sisa / Piutang'; selisihText.textContent=rupiah(Math.abs(diff));} }
 qty.addEventListener('input', function(){ if(Number(qty.value)<1) qty.value=1; uang.value=Math.round(total()); refresh(); });
 uang.addEventListener('input', refresh);
 document.getElementById('qtyMinus').onclick=()=>{qty.value=Math.max(1,Number(qty.value||1)-1); uang.value=Math.round(total()); refresh();};
 document.getElementById('qtyPlus').onclick=()=>{qty.value=Number(qty.value||1)+1; uang.value=Math.round(total()); refresh();};
 document.getElementById('btnLunas').onclick=()=>{ uang.value=Math.round(total()); metodeInputs.forEach(i=>{if(i.value==='Cash')i.checked=true}); refresh(); };
 document.getElementById('btnDp50').onclick=()=>{ uang.value=Math.round(total()/2); refresh(); };
 document.getElementById('btnUtang').onclick=()=>{ uang.value=0; metodeInputs.forEach(i=>{if(i.value==='Utang')i.checked=true}); refresh(); };
 metodeInputs.forEach(i=>i.addEventListener('change',()=>{ if(i.checked && i.value==='Utang'){ uang.value=0; refresh(); } }));
 const search=document.getElementById('customerSearch'), menu=document.getElementById('customerMenu'), hidden=document.getElementById('kodePelangganInput');
 function items(){ return Array.from(menu.querySelectorAll('.pa-customer-item')); }
 function openMenu(){ menu.style.display='block'; filter(); }
 function closeMenu(){ setTimeout(()=>menu.style.display='none',180); }
 function choose(el){ hidden.value=el.dataset.kode; search.value=el.dataset.label; menu.style.display='none'; }
 function filter(){ const q=search.value.toLowerCase().trim(); let shown=0; items().forEach(el=>{ const txt=(el.textContent||'').toLowerCase(); const ok=!q || txt.includes(q); el.style.display=ok?'block':'none'; if(ok) shown++; }); }
 search.addEventListener('focus',openMenu); search.addEventListener('click',openMenu); search.addEventListener('blur',closeMenu); search.addEventListener('input',()=>{ hidden.value='UMUM'; filter(); openMenu(); });
 items().forEach(el=>el.addEventListener('mousedown',e=>{e.preventDefault(); choose(el);}));
 document.getElementById('kasirForm').addEventListener('submit',function(e){ if(!confirm('Buat transaksi kasir dari hasil analyzer ini?')) e.preventDefault(); });
 refresh();
})();
</script>
<?php elseif($batchCount > 1 && empty($job['no_penjualan'])): ?><div class="alert alert-info">File ini bagian dari upload multi-file. Buat transaksi dari <a href="batch.php?token=<?= urlencode($job['batch_token']) ?>">Ringkasan Gabungan</a> agar semua file dihitung menjadi satu.</div><?php else: ?><div class="alert alert-success">Sudah menjadi transaksi: <b><?= e($job['no_penjualan']) ?></b> · <a href="../penjualan/cetak.php?no=<?= urlencode($job['no_penjualan']) ?>">Cetak Nota</a></div><?php endif; ?>
<div class="card border-0 shadow-sm"><div class="card-header bg-white"><b>Preview & Koreksi Per Halaman</b><br><small class="text-muted">Saat kategori disimpan, analyzer_settings ikut belajar otomatis.</small></div><div class="card-body"><div class="row g-3"><?php foreach($pages as $page): ?><div class="col-md-3 col-sm-6"><div class="preview-card h-100"><img loading="lazy" src="preview.php?job=<?= $id ?>&file=<?= urlencode($page['preview_filename']) ?>"><div class="mt-2"><b>Halaman <?= (int)$page['page_number'] ?></b><br><small class="text-muted">Warna <?= e($page['colored_pixel_percentage']) ?>% · Isi <?= e($page['nonwhite_pixel_percentage']) ?>%</small><form method="post" action="override.php" class="mt-2"><input type="hidden" name="_csrf" value="<?= e(pa_csrf()) ?>"><input type="hidden" name="job_id" value="<?= $id ?>"><input type="hidden" name="page_id" value="<?= (int)$page['id'] ?>"><select class="form-select form-select-sm mb-2" name="category"><?php foreach(pa_setting('categories',[]) as $k=>$label): ?><option value="<?= e($k) ?>" <?= $page['final_category']===$k?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select><button class="btn btn-sm btn-outline-primary w-100">Simpan</button></form><?php if((int)$page['overridden']===1): ?><span class="badge bg-warning text-dark mt-2">Manual</span><?php endif; ?><div class="fw-bold mt-2"><?= rupiah($page['unit_price']) ?></div></div></div></div><?php endforeach; ?></div></div></div>
<?php require __DIR__.'/_footer.php'; ?>
